# Generated by Django 5.0.6 on 2024-12-30 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHallCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunAndActivitiesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_food_and_beverage', models.BooleanField(default=False)),
                ('is_active_conversation_hall', models.BooleanField(default=False)),
                ('is_active_fun_and_activities', models.BooleanField(default=False)),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='accounts.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='FunAndActivitiesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='fun_and_activities/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activity_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_posts', to='events.funandactivitiescategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FoodAndBeveragePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='food_and_beverage/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('food_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_posts', to='events.foodcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationHallPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='conversation_hall/')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hall_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_posts', to='events.conversationhallcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AdminApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('food_and_beverage', 'Food and Beverage'), ('conversation_hall', 'Conversation Hall'), ('fun_and_activities', 'Fun and Activities')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.organization')),
            ],
            options={
                'unique_together': {('organization', 'tag', 'is_approved')},
            },
        ),
    ]
