# Generated by Django 5.0.6 on 2025-01-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0002_postfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfeedback',
            name='post',
        ),
        migrations.AddField(
            model_name='postfeedback',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='postfeedback',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
