# Generated by Django 5.0.6 on 2025-01-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_postfeedback_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminapprovalrequest',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Admin Approval Request', 'verbose_name_plural': 'Admin Approval Requests'},
        ),
        migrations.AlterUniqueTogether(
            name='adminapprovalrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adminapprovalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Removed', 'Removed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='adminapprovalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminapprovalrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='events.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='adminapprovalrequest',
            unique_together={('organization', 'tag')},
        ),
    ]
