# Generated by Django 5.0.6 on 2025-01-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_organization_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationhallpost',
            old_name='price_per_hour',
            new_name='price',
        ),
    ]
