# Generated by Django 5.0.6 on 2025-01-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_price_per_hour_conversationhallpost_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationhallpost',
            old_name='images',
            new_name='image',
        ),
    ]
